Add resource limits for upgrade and delete hook batch jobs
spiffe/helm-charts-hardened pull request #366
Opened 2024-05-26 15:24 UTC by kfox1111

Updated pr: https://github.com/spiffe/helm-charts-hardened/pull/322 here since it is unwritable.

2024-06-18 15:34 UTC, edwbuck requested changes
Requesting clarity on the desired "resource" comments and "commenting pattern"

This is because the pattern itself doesn't align with our desires, as we don't want people editing this file, and the helm chart itself doesn't need an object defined here (because we are using better practices than were there originally).

2024-06-19 17:36 UTC, kfox1111 commented on charts/spire/values.yaml
> +    resources: {}
updated as discussed in the meeting yesterday.

2024-06-19 18:02 UTC, edwbuck approved these changes
Apparently the desire is to keep the resources pattern as-is.  This is deduced by the comment "updated in accordance to the meeting (of June 18th)" where the meeting held the door open for any desired improvements.

Approving

2024-06-19 18:06 UTC, edwbuck commented
@kfox1111 There are failures in the checks.  It looks like some logic is cutting off the first letter of the name of the host in one test suite.  Maybe that's because it assumed a https:// prefix somewhere, and the prefix is http://?  Please look into it and see if this can be fixed prior to merge.

2024-06-19 18:25 UTC, kfox1111 commented
There s a race that happens occasionally. Retesting the failed job in that case resolves it. There is an open issue to fix it.

2024-06-19 19:50 UTC, merged